[tool.poetry]
name = "endgame-launcher"
version = "0.1.0"
description = "EndGame Launcher Application"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
