name: Run make push

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  make-push:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      IMAGE_URL: ${{ secrets.IMAGE_URL }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Needed to get the full git history for rev-parse
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Run make push
      run: |
        cd py-endgame-aws
        echo '${{ secrets.BATCH_CORE_CONFIG }}' > config.json
        make push TAG=${GITHUB_SHA::7}
